### ISSUE TITLE
Error Using Package. Not Able to Install Pods

### ISSUE THREAD

**Issue by eopeter** [LeonidVeremchuk/flutter-apple-pay#2]
Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "flutter_apple_pay":
      In Podfile:
        flutter_apple_pay (from `.symlinks/plugins/flutter_apple_pay/ios`)
    Specs satisfying the `flutter_apple_pay (from `.symlinks/plugins/flutter_apple_pay/ios`)` dependency were found, but they required a higher minimum deployment target.

My Deployment Target was 9.0. Changed to 11.0 and still get error message

**Comment by UmairRehmat** [comment]
how you resolved this issue

**Comment by dineshkokare123** [comment]
Can you tell whats the resolution.
